C:dict = {"C": "Maj", "D": "Min","E": "Min", "F": "Maj", "G": "Maj","A":"Min","B":"Dim"}
C_diesis:dict = {"C#": "Maj", "D#": "Min","F": "Min", "F#": "Maj", "G#": "Maj","A#":"Min","C":"Dim"}
D:dict = {"D": "Maj", "E": "Min","F#": "Min", "G": "Maj", "A":"Maj","B":"Min","C#":"Dim"}
D_diesis:dict = {"D#": "Maj", "F": "Min","G": "Min", "G#":"Maj","A#":"Maj","C":"Min","D":"Dim"}
E:dict = {"E": "Maj", "F#": "Min","G#": "Min", "A":"Maj","B":"Maj","C#":"Min","D#":"Dim"}
F:dict = {"F": "Maj", "G": "Min","A": "Min", "A#":"Maj","C":"Maj","D":"Min","E":"Dim"}
F_diesis:dict = {"F#": "Maj", "G#": "Min","A#": "Min", "B":"Maj","C#":"Maj","D#":"Min","F":"Dim"}
G:dict = {"G": "Maj", "A": "Min","B": "Min", "C":"Maj","D":"Maj","E":"Min","F#":"Dim"}
G_diesis:dict = {"G#": "Maj", "A#": "Min","C": "Min", "C#":"Maj","D#":"Maj","F":"Min","G":"Dim"}
A:dict= {"A": "Maj", "B": "Min","C#": "Min", "D":"Maj","E":"Maj","F":"Min","G#":"Dim"}
A_diesis:dict= {"A#": "Maj", "C": "Min","D": "Min", "D#":"Maj","F":"Maj","G":"Min","A":"Dim"}
B:dict= {"B": "Maj", "C#": "Min","D#": "Min", "E":"Maj","F#":"Maj","G#":"Min","A#":"Dim"}

while True:
    scelta:str = input("Digita un accordo: ")