'''Your Own List: Think of your favorite mode of transportation, such as a motorcycle or a car, and make a list that stores several examples. 
Use your list to print a series of statements about these items, such as “I would like to own a Honda motorcycle.”'''

veicoli:list = ["Wolkswagen Golf", "Mustang 1969", "Jeep Renegade", "Peugeot 2008"]

for auto in veicoli:
    print(f"I would like to own a {auto}")





