'''Your Own List: Think of your favorite mode of transportation, such as a motorcycle or a car, and make a list that stores several examples. 
Use your list to print a series of statements about these items, such as “I would like to own a Honda motorcycle.”'''

veicoli:list[str] = ["Wolkswagen Golf", "Mustang 1969", "Jeep Renegade", "Peugeot 2008"]


print(f"I would like to own a {veicoli[0]}")
print(f"I would like to own a {veicoli[1]}")
print(f"I would like to own a {veicoli[2]}")
print(f"I would like to own a {veicoli[3]}")






