FROM python:3.10.12

RUN mkdir /app
COPY main.py /app
COPY Classe_Studente.py /app
COPY Classe_Room.py /app
COPY Classe_Persona.py /app
COPY Classe_Insegnante.py /app
COPY Classe_Gruppo.py /app
COPY Classe_Corso.py /app
COPY Classe_Building.py /app

WORKDIR /app


